main – Fortran 2018 examples
main Program
12 statements
Source File
Uses
mpi_f08
Calls
Contents
Variables
ierr mrank msize vlen version
Variables
Type Attributes Name Initial
integer :: ierr
integer :: mrank
integer :: msize
integer :: vlen
character(len=MPI_MAX_LIBRARY_VERSION_STRING) :: version
Call graph
main calls mpi_finalize, mpi_init, mpi_comm_rank, mpi_comm_size, mpi_get_library_version