randominit – Fortran 2018 examples
randominit Program
11 statements
Source File
Uses
random
Calls
Contents
Variables
r i
Variables
Type Attributes Name Initial
real :: r
integer :: i
Call graph
randominit calls random_init
random_init calls random_init, randint