rot90_array – Fortran 2018 examples
rot90_array Program
33 statements
Source File
Uses
rotflip
Calls
Contents
Variables
N i iarr Barr rarr
Subroutines
printarr
Variables
Type Attributes Name Initial
integer, parameter :: N = 3
integer :: i
integer :: iarr(N,N)
integer :: Barr(0:2,0:2)
real :: rarr(N,N)
Subroutines
subroutine printarr(arr, msg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: arr(:,:)
character(len=*), intent(in), optional :: msg
Call graph
rot90_array calls printarr, fliplr, rot90, flipud
fliplr calls fliplr_r, fliplr_i
rot90 calls rot90_i, rot90_r
flipud calls flipud_i, flipud_r
rot90_i calls flip
rot90_r calls flip
flipud_i calls flip
fliplr_r calls flip
flipud_r calls flip
fliplr_i calls flip
flip calls flip_r, flip_i