RWDSET_FORTRAN2003 – Fortran 2018 examples
RWDSET_FORTRAN2003 Program
95 statements
Source File
Uses
iso_c_binding
HDF5
Calls
Contents
Variables
i1 i4 i8 i16 sp dp filename dsetname1 dsetname2 dsetname4 dsetname8 dsetnamer4 dsetnamer8 file_id dset_id1 dset_id4 dset_id8 dset_id16 dset_idr4 dset_idr8 error i dset_data_i1 dset_data_i4 data_out_i4 dset_data_i8 data_out_i8 dset_data_i16 data_out_i16 data_out_i8a dset_data_r7 data_out_r7 dset_data_r15 data_out_r15 data_dims dspace_id f_ptr
Variables
Type Attributes Name Initial
integer, parameter :: i1 = SELECTED_INT_KIND(2)
integer, parameter :: i4 = SELECTED_INT_KIND(4)
integer, parameter :: i8 = SELECTED_INT_KIND(9)
integer, parameter :: i16 = SELECTED_INT_KIND(18)
integer, parameter :: sp = SELECTED_REAL_KIND(6, 37)
integer, parameter :: dp = SELECTED_REAL_KIND(15, 307)
character(len=*), parameter :: filename = "dsetf.h5"
character(len=*), parameter :: dsetname1 = "dset1"
character(len=*), parameter :: dsetname2 = "dset2"
character(len=*), parameter :: dsetname4 = "dset4"
character(len=*), parameter :: dsetname8 = "dset8"
character(len=*), parameter :: dsetnamer4 = "dsetr4"
character(len=*), parameter :: dsetnamer8 = "dsetr8"
integer(kind=HID_T) :: file_id
integer(kind=HID_T) :: dset_id1
integer(kind=HID_T) :: dset_id4
integer(kind=HID_T) :: dset_id8
integer(kind=HID_T) :: dset_id16
integer(kind=HID_T) :: dset_idr4
integer(kind=HID_T) :: dset_idr8
integer :: error
integer :: i
integer(kind=i1), DIMENSION(1:4), TARGET :: dset_data_i1
integer(kind=i4), DIMENSION(1:4), TARGET :: dset_data_i4
integer(kind=i4), DIMENSION(1:4), TARGET :: data_out_i4
integer(kind=i8), DIMENSION(1:4), TARGET :: dset_data_i8
integer(kind=i8), DIMENSION(1:4), TARGET :: data_out_i8
integer(kind=i16), DIMENSION(1:4), TARGET :: dset_data_i16
integer(kind=i16), DIMENSION(1:4), TARGET :: data_out_i16
integer(kind=i8), DIMENSION(1:4), TARGET :: data_out_i8a
real(kind=sp), DIMENSION(1:4), TARGET :: dset_data_r7
real(kind=sp), DIMENSION(1:4), TARGET :: data_out_r7
real(kind=dp), DIMENSION(1:4), TARGET :: dset_data_r15
real(kind=dp), DIMENSION(1:4), TARGET :: data_out_r15
integer(kind=HSIZE_T), DIMENSION(1:1) :: data_dims = (/4/)
integer(kind=HID_T) :: dspace_id
type(C_PTR) :: f_ptr
Call graph
rwdset_fortran2003 calls h5screate_simple_f, h5open_f, h5kind_to_type, h5fopen_f, h5dclose_f, h5fclose_f, h5fcreate_f, h5close_f