testall – Fortran 2018 examples
testall Program
27 statements
Source File
Uses
ieee_arithmetic
iso_fortran_env
fib3
assert
Calls
Contents
Variables
pi nan inf
Variables
Type Attributes Name Initial
real(kind=wp), parameter :: pi = 4.*atan(1._wp)
real(kind=wp) :: nan
real(kind=wp) :: inf
Call graph
testall calls isclose, assert_isclose, fib
assert_isclose calls isclose