test2 – Fortran 2018 examples
test2 Program
8 statements
Source File
Uses
funcs
Calls
Contents
Variables
twos twod twoi
Variables
Type Attributes Name Initial
real(kind=sp) :: twos = 2._sp
real(kind=dp) :: twod = 2._dp
integer :: twoi = 2
Call graph
test2 calls addtwo
addtwo calls addtwo_i, addtwo_s, addtwo_d