h5rw – Fortran 2018 examples
h5rw Program
46 statements
Source File
Uses
iso_fortran_env
hdf5
Calls
Contents
Variables
filename dsname fid dset_id dspace_id mspace_id data_dims sp dp ioerr i din dout f_ptr array
Variables
Type Attributes Name Initial
character(len=*), parameter :: filename = "simple.h5"
character(len=*), parameter :: dsname = "my_image"
integer(kind=hid_t) :: fid
integer(kind=hid_t) :: dset_id
integer(kind=hid_t) :: dspace_id
integer(kind=hid_t) :: mspace_id
integer(kind=hsize_t) :: data_dims(rank)
integer, parameter :: sp = selected_real_kind(6, 37)
integer, parameter :: dp = selected_real_kind(15, 307)
integer :: ioerr
integer :: i
real(kind=dp), target :: din(9)
real(kind=dp), target :: dout(9)
type(c_ptr) :: f_ptr
real(kind=dp) :: array(9)
Call graph
h5rw calls h5screate_simple_f, h5open_f, h5kind_to_type, h5fopen_f, h5dclose_f, h5fclose_f, h5fcreate_f, h5close_f