hdf5simple – Fortran 2018 examples
hdf5simple Program
24 statements
Source File
Uses
iso_fortran_env
h5mod
Calls
Contents
Variables
filename dsname array length ioerr argv
Functions
fakedata
Variables
Type Attributes Name Initial
character(len=*), parameter :: filename = "simple.h5"
character(len=*), parameter :: dsname = "1toN"
real(kind=dp), allocatable :: array(:)
integer :: length
integer :: ioerr
character(len=8) :: argv
Functions
function fakedata(length)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: length
Return Value real(kind=dp) (length)
Call graph
hdf5simple calls h5write, fakedata
h5write calls h5fclose_f, h5fcreate_f, h5open_f