helloworld – Fortran 2018 examples
helloworld Program
20 statements
Source File
Uses
mpi_f08
iso_fortran_env
Calls
Contents
Variables
i Nproc wtime
Variables
Type Attributes Name Initial
integer :: i
integer :: Nproc
real(kind=dp) :: wtime
Call graph
helloworld calls mpi_wtime, mpi_finalize, mpi_init, mpi_comm_rank, mpi_comm_size