lite_test – Fortran 2018 examples
lite_test Program
7 statements
Source File
Calls
Contents
None
Call graph
lite_test calls test_datasets, test_attributes, test_dataset1d, test_dataset2d, test_dataset3d
test_datasets calls passed, h5ltread_dataset_double_f, h5ltget_dataset_info_f, h5ltmake_dataset_float_f, h5ltread_dataset_float_f, h5ltmake_dataset_string_f, h5ltget_dataset_ndims_f, h5fcreate_f, h5ltfind_dataset_f, h5fclose_f, h5close_f, test_begin, h5ltmake_dataset_int_f, h5ltread_dataset_int_f, h5open_f, h5ltmake_dataset_double_f, h5ltread_dataset_string_f
test_attributes calls passed, h5ltset_attribute_string_f, h5ltget_attribute_string_f, h5ltget_attribute_float_f, h5ltset_attribute_int_f, h5fcreate_f, h5fclose_f, h5close_f, h5ltget_attribute_ndims_f, test_begin, h5ltmake_dataset_int_f, h5ltget_attribute_double_f, h5ltset_attribute_float_f, h5open_f, h5ltget_attribute_info_f, h5ltget_attribute_int_f, h5ltset_attribute_double_f
test_dataset1d calls passed, h5fcreate_f, h5fclose_f, h5close_f, test_begin, h5ltmake_dataset_f, h5open_f, h5ltread_dataset_f
test_dataset2d calls passed, h5fcreate_f, h5fclose_f, h5close_f, test_begin, h5ltmake_dataset_f, h5open_f, h5ltread_dataset_f
test_dataset3d calls passed, h5ltget_dataset_info_f, h5fcreate_f, h5fclose_f, h5close_f, test_begin, h5ltmake_dataset_f, h5open_f, h5ltread_dataset_f