main – Fortran 2018 examples
main Program
44 statements
Source File
Uses
iso_fortran_env
mpi_f08
Calls
Contents
Variables
time mcount dat val dest i num_procs rank tag status
Variables
Type Attributes Name Initial
character(len=10) :: time
integer :: mcount
real :: dat(0:99)
real :: val(200)
integer :: dest
integer :: i
integer :: num_procs
integer :: rank
integer :: tag
type(MPI_STATUS) :: status
Call graph
main calls mpi_finalize, mpi_init, mpi_get_count, mpi_comm_rank, mpi_comm_size