simple_xy_rd – Fortran 2018 examples
simple_xy_rd Program
27 statements
Source File
Uses
netcdf
Calls
Contents
Variables
fn NX NY data_in ncid varid x y
Subroutines
check
Variables
Type Attributes Name Initial
character(len=*), parameter :: fn = "simple_xy.nc"
integer, parameter :: NX = 6
integer, parameter :: NY = 12
integer :: data_in(NY,NX)
integer :: ncid
integer :: varid
integer :: x
integer :: y
Subroutines
subroutine check(status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
Call graph
simple_xy_rd calls nf90_inq_varid, nf90_get_var, nf90_close, nf90_open