simple_xy_wr – Fortran 2018 examples
simple_xy_wr Program
45 statements
Source File
Uses
netcdf
Calls
Contents
Variables
fn NDIMS NX NY ncid varid dimids x_dimid y_dimid dout dat x y
Subroutines
writenc readnc check
Variables
Type Attributes Name Initial
character(len=*), parameter :: fn = "simple_xy.nc"
integer, parameter :: NDIMS = 2
integer, parameter :: NX = 6
integer, parameter :: NY = 12
integer :: ncid
integer :: varid
integer :: dimids(NDIMS)
integer :: x_dimid
integer :: y_dimid
integer :: dout(NY,NX)
integer :: dat(ny,nx)
integer :: x
integer :: y
Subroutines
subroutine writenc(fn, dout)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fn
integer, intent(in) :: dout(:,:)
subroutine readnc(fn, dat)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fn
integer, intent(out) :: dat(:,:)
subroutine check(status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
Call graph
simple_xy_wr calls readnc, writenc
readnc calls nf90_get_var, nf90_close, nf90_inq_varid, nf90_open
writenc calls nf90_put_var, nf90_close, nf90_def_var, nf90_def_dim, nf90_enddef, nf90_create