wait_precision – Fortran 2018 examples
wait_precision Program
22 statements
Source File
Uses
iso_fortran_env
Calls
Contents
Variables
tic toc rate
Subroutines
timempi
Variables
Type Attributes Name Initial
integer(kind=int64) :: tic
integer(kind=int64) :: toc
integer(kind=int64) :: rate
Subroutines
subroutine timempi()
Arguments
None
Call graph
wait_precision calls timempi
timempi calls omp_get_wtick, omp_get_wtime, omp_get_num_procs, omp_get_num_threads, omp_get_thread_num