flip_i – Fortran 2018 examples
flip_i Function
18 statements
Source File
public function flip_i(A, d) result(flip)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A(:,:)
integer, intent(in) :: d
Return Value integer
Called by
Contents
None
Call graph
flip calls flip_i
rot90_i calls flip
rot90_r calls flip
flipud_i calls flip
fliplr_r calls flip
flipud_r calls flip
fliplr_i calls flip
fliplr calls fliplr_r, fliplr_i
rot90 calls rot90_i, rot90_r
flipud calls flipud_i, flipud_r
rot90_array calls fliplr, rot90, flipud