readnc – Fortran 2018 examples
readnc Subroutine
9 statements
Source File
subroutine readnc(fn, dat)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fn
integer, intent(out) :: dat(:,:)
Calls
Called by
Contents
None
Call graph
readnc calls nf90_inq_varid, nf90_get_var, nf90_close, nf90_open
simple_xy_wr calls readnc