test_datasets – Fortran 2018 examples
test_datasets Subroutine
106 statements
Source File
subroutine test_datasets()
Uses
H5LT
HDF5
Arguments
None
Calls
Called by
Contents
None
Call graph
test_datasets calls h5ltmake_dataset_int_f, h5ltread_dataset_float_f, h5ltread_dataset_int_f, h5ltfind_dataset_f, h5open_f, h5ltmake_dataset_double_f, h5ltmake_dataset_string_f, h5ltget_dataset_ndims_f, passed, h5ltread_dataset_double_f, h5ltget_dataset_info_f, h5ltmake_dataset_float_f, h5fclose_f, h5fcreate_f, h5ltread_dataset_string_f, h5close_f, test_begin
lite_test calls test_datasets