test_dataset3D – Fortran 2018 examples
test_dataset3D Subroutine
106 statements
Source File
subroutine test_dataset3D()
Uses
H5LT
HDF5
Arguments
None
Calls
Called by
Contents
None
Call graph
test_dataset3d calls h5ltmake_dataset_f, h5open_f, h5ltread_dataset_f, passed, h5ltget_dataset_info_f, h5fclose_f, h5fcreate_f, h5close_f, test_begin
lite_test calls test_dataset3d