timempi – Fortran 2018 examples
timempi Subroutine
13 statements
Source File
subroutine timempi()
Uses
omp_lib
Arguments
None
Calls
Called by
Contents
None
Call graph
timempi calls omp_get_wtick, omp_get_wtime, omp_get_num_procs, omp_get_num_threads, omp_get_thread_num
wait_precision calls timempi