writenc – Fortran 2018 examples
writenc Subroutine
12 statements
Source File
subroutine writenc(fn, dout)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fn
integer, intent(in) :: dout(:,:)
Calls
Called by
Contents
None
Call graph
writenc calls nf90_put_var, nf90_close, nf90_def_var, nf90_enddef, nf90_def_dim, nf90_create
simple_xy_wr calls writenc