fliplr_i – Fortran 2018 examples
fliplr_i Function
5 statements
Source File
public function fliplr_i(A) result(fliplr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A(:,:)
Return Value integer
Calls
Called by
Contents
None
Call graph
fliplr_i calls flip
flip calls flip_r, flip_i
fliplr calls fliplr_i
rot90_array calls fliplr