test_begin – Fortran 2018 examples
test_begin Subroutine
5 statements
Source File
subroutine test_begin(string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Called by
Contents
None
Call graph
test_datasets calls test_begin
test_attributes calls test_begin
test_dataset1d calls test_begin
test_dataset2d calls test_begin
test_dataset3d calls test_begin
lite_test calls test_datasets, test_attributes, test_dataset1d, test_dataset2d, test_dataset3d