test_attributes – Fortran 2018 examples
test_attributes Subroutine
101 statements
Source File
subroutine test_attributes()
Uses
H5LT
HDF5
Arguments
None
Calls
Called by
Contents
None
Call graph
test_attributes calls h5ltmake_dataset_int_f, h5ltget_attribute_double_f, h5ltset_attribute_float_f, h5ltset_attribute_double_f, h5open_f, h5ltget_attribute_info_f, test_begin, h5ltget_attribute_float_f, passed, h5ltset_attribute_int_f, h5ltset_attribute_string_f, h5fclose_f, h5close_f, h5ltget_attribute_int_f, h5ltget_attribute_ndims_f, h5ltget_attribute_string_f, h5fcreate_f
lite_test calls test_attributes