flipud – Fortran 2018 examples
flipud Interface
3 statements
Source File
public interface flipud
Calls
Called by
Contents
Module Procedures
flipud_i flipud_r
Module Procedures
public function flipud_i(A) result(flipud)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A(:,:)
Return Value integer
public function flipud_r(A) result(flipud)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(:,:)
Return Value real
Call graph
flipud calls flipud_i, flipud_r
flipud_i calls flip
flipud_r calls flip
flip calls flip_r, flip_i
rot90_array calls flipud