name: fpm

on:
  push:
    paths:
      - "**.f90"
      - "fpm.toml"
      - ".github/workflows/fpm.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - uses: fortran-lang/setup-fpm@v9
      with:
        fpm-version: "current"

    - uses: actions/checkout@v6

    - run: fpm build

# fpm test doesn't have a way to feature test
