name: oneapi-linux
# debug triggers asan build errors, peculiar to GitHub Actions

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.c"
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/oneapi-linux.yml"
      - ".github/workflows/oneapi*.sh"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: fortran-lang/setup-fortran@v1
      with:
        compiler: intel
        version: latest
# need 'latest' else the oldest available version gets installed

    - uses: actions/checkout@v7

    - run: cmake --workflow default

    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: oneapi-${{ runner.os }}-CMakeConfigureLog.yaml
        path: build/CMakeFiles/CMakeConfigureLog.yaml
