name: oneapi-linux

env:
  FC: ifx
# https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja
# don't need Ninja but it prints the command lines by default which is good for debugging

  # debug triggers asan build errors, peculiar to GitHub Actions

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.c"
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/oneapi-linux.yml"
      - ".github/workflows/oneapi*.sh"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        oneapi: [2025.2]
    steps:
    - uses: actions/checkout@v5

    - name: cache install oneAPI
      id: cache-install
      uses: actions/cache@v4
      with:
        path: |
          /opt/intel/oneapi
        key: oneapi-${{ matrix.oneapi }}-apt

    - name: non-cache install oneAPI
      if: steps.cache-install.outputs.cache-hit != 'true'
      timeout-minutes: 5
      run: |
        .github/workflows/oneapi_setup_apt_repo_linux.sh
        sudo apt install --no-install-recommends intel-oneapi-compiler-fortran-${{ matrix.oneapi }}

    - name: Setup Intel oneAPI environment
      run: |
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV

    - name: Configure, build, test CMake workflow
      run: cmake --workflow default

    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: oneapi-${{ matrix.oneapi }}-${{ runner.os }}-CMakeConfigureLog.yaml
        path: build/CMakeFiles/CMakeConfigureLog.yaml

    - name: exclude unused files from cache
      if: steps.cache-install.outputs.cache-hit != 'true'
      run: .github/workflows/oneapi_cache_exclude_linux.sh
